robot1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 

    extra_joints:
      - name:     'base_to_wheel1'
      - name:     'base_to_wheel2'
      - name:     'base_to_wheel3'
      - name:     'base_to_wheel4'
      - name:     'zaxis_to_support'

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint1_b
    pid: {p: 600.0, i: 10.0, d: 0.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Joint2_b
    pid: {p: 600.0, i: 10.0, d: 0.0}

